### ISSUE TITLE
calling start() on an already playing instance crashes application

### ISSUE THREAD

**Issue by avilleret** [jvcleave/ofxOMXPlayer#141]
it crashes with a weird backtrace : 

```
Thread 11 "video_player-ar" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x68809140 (LWP 2949)]
0x75cdaa08 in ?? () from /usr/lib/arm-linux-gnueabihf/libavformat.so.57
(gdb) bt
#0  0x75cdaa08 in ?? () from /usr/lib/arm-linux-gnueabihf/libavformat.so.57
#1  0x75cda9fc in ?? () from /usr/lib/arm-linux-gnueabihf/libavformat.so.57
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

code to reproduce (modified example-basic setup() function) :

```
  string videoPath = ofToDataPath("/home/pi/big_buck_bunny_720p_h264.mov", true);
  ofLog() << "videoPath: " << videoPath;
  //Somewhat like ofFboSettings we may have a lot of options so this is the current model
  ofxOMXPlayerSettings settings;
  settings.useHDMIForAudio = true;	//default true
  settings.enableTexture = true;		//default true
  settings.enableLooping = true;		//default true
  settings.enableAudio = true;		//default true, save resources by disabling
  settings.doFlipTexture = true;		//default false
	
  //so either pass in the settings
  omxPlayer.setup(settings);

  omxPlayer.loadMovie(videoPath);
  omxPlayer.start();
```

**Comment by jvcleave** [comment]
Yeah - I can see how this could get confusing

if you want to use start() you should use:
```
settings.autoStart=false;
settings.videoPath = videoPath;
omxPlayer.setup(settings);
omxPlayer.start();
```
